default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password:
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  # `.where('started_at < ?', Date.tomorrow + 1.day + 5.hours)` というメソッドを実行すると
  # エラーになったので、prepared_statementsをfalseにする
  # http://stackoverflow.com/questions/21035561/why-am-i-getting-these-postgresql-errors-since-upgrading-to-rails-4
  prepared_statements: false

development:
  <<: *default
  database: annict_development
  host: db

test:
  <<: *default
  database: annict_test
  host: localhost

production:
  <<: *default
  database: annict_production
